source "https://rubygems.org"
gem "jekyll", "~> 4.3.0"
gem "just-the-docs"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-readme-index"
gem "jekyll-optional-front-matter"
gem "jekyll-titles-from-headings"
